import pycli

pycli.cmd("config\r\n")
pycli.cmd("ip access-list extended 2000\r\n")
pycli.cmd("10 deny tcp any any eq 445\r\n")
pycli.cmd("20 deny tcp any any eq 135\r\n")
pycli.cmd("30 deny tcp any any eq 137\r\n")
pycli.cmd("40 deny tcp any any eq 138\r\n")
pycli.cmd("50 deny tcp any any eq 139\r\n")
pycli.cmd("60 deny udp any any eq 445\r\n")
pycli.cmd("70 deny udp any any eq 135\r\n")
pycli.cmd("80 deny udp any any eq 137\r\n")
pycli.cmd("90 deny udp any any eq 138\r\n")
pycli.cmd("100 deny udp any any eq 139\r\n")
pycli.cmd("110 permit ip any any\r\n")
pycli.cmd("exit\r\n")
pycli.cmd("ip session filter 2000\r\n")
pycli.cmd("end\r\n")
pycli.cmd("write\r\n")